baseURL = "/"
languageCode = "en-us"
title = "RBLB"
paginate=9
summarylength = 20
enableRobotsTXT = true
ignoreErrors = ["error-output-taxonomy"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  avatar="https://github.com/riccardobl.png"
  avatarCache="/images/avatar.webp"
  favicon = "favicon.p5img.js.png"
  description = ""
  youtube = "https://www.youtube.com/channel/UCh_H0NPkra9GZU_KFC5eVbw"
  github = "https://github.com/riccardobl"
  header = "/images/header.webp"
  email="riccardo0blb@gmail.com"
  twitter="i/user/1260924338632564739"
  custom_css = ["/css/style.css"]
  custom_js=["/js/script.js"]
  discord_user="rblb#9882"

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML"]
  taxonomy = ["HTML","JSON"]
  term=["HTML","JSON"]

