#   CLOUDFLARE_WORKER_NAME = "comments"
#   CLOUDFLARE_WORKER_URL = "https://comments.rblb.workers.dev"
#   CLOUDFLARE_USER_ID="XXXX"
#   CLOUDFLARE_API_KEY="XXXX"
#   CLOUDFLARE_ZONE="XXXX"
#   SHADERTOY_KEY= "XXXX"
#   YOUTUBE_KEY= "XXXX"
#   TWITTER_CONSUMER_KEY= "XXXX"
#   TWITTER_CONSUMER_SECRET= "XXXX"
#   TWITTER_ACCESS_TOKEN_KEY= "XXXX"
#   TWITTER_ACCESS_TOKEN_SECRET= "XXXX"
#   DROPBOX_APIKEY= "XXXX"
#   BOT_TOKEN  a personal access token that will be used when creating GitHub issues. https://github.com/settings/tokens/new?scopes=public_repo
#   CLIENT_ID The client id to be used in the GitHub OAuth web application flow https://developer.github.com/v3/oauth/#web-application-flow
#   CLIENT_SECRET The client secret for the OAuth web application flow
#   STATE_PASSWORD 32 character password for encrypting state in request headers/cookies.
name: Build
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - project
jobs:
  build:
    runs-on: ubuntu-latest   
    container:
      image: riccardoblb/buildenvs:hugo
    env:
      SHADERTOY_USER: rblb
      YOUTUBE_CHANNEL: UCh_H0NPkra9GZU_KFC5eVbw
      GITHUB_ACCOUNTS: riccardobl,jmePhonon,f3b
      TWITTER_COLLECTION:  ${{ secrets.TWITTER_COLLECTION }}
      DROPBOX_FOLDERS: devlog
      SHADERTOY_KEY: ${{ secrets.SHADERTOY_KEY }}
      YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      DROPBOX_APIKEY: ${{ secrets.DROPBOX_APIKEY }}

    steps: 
    - name: Clone repo
      run: |
          git config --global user.name "GithubActions"
          git config --global user.email "actions@robot.frk.wf"
          git clone --single-branch  --depth 1 --recurse-submodules  --branch project https://github.com/${GITHUB_REPOSITORY}.git project

    - name: Prepare dist dir
      run: |
          git config --global user.name "GithubActions"
          git config --global user.email "actions@robot.frk.wf"
          git clone --no-checkout --single-branch --branch master https://github.com/${GITHUB_REPOSITORY}.git generated    
          cd generated
          git reset --hard `git rev-list --max-parents=0 HEAD`
          cd ..


    - name: Build
      run: |
        cd project
        chmod +x ./make.sh
        NO_P5RENDER=1 NO_CONTAINER=1 HEADLESS=1 ./make.sh         
        mkdir -p public
        echo "1" > public/.nojekyll

    - name: Deploy   
      shell: bash  
      run: |
        shopt -s dotglob
        cp -Rf project/public/* generated/
        cd generated
        git add .
        git commit -m "Update data - `date`"        
        header=$(echo -n "ad-m:${{ secrets.GITHUB_TOKEN }}" | base64)
        set +e
        (git -c http.extraheader="AUTHORIZATION: basic $header" push origin master --force )

    - name: Purge Cloudflare Cache
      shell: bash
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
        -H "Content-Type: application/json"  --data '{"purge_everything":true}' 

        
